@startuml
'https://plantuml.com/class-diagram

interface IDomainEntity{
    domainProperty: Int
    domainOperation()
}
class DomainEntity
DomainEntity -r-|> IDomainEntity

interface IRepository{
    save()
    get()
    delete()
}

class Repository
IRepository <|-l- Repository
note bottom of Repository: Реализует \nработу с БД

interface IPresenter{
    presentResult()
}

class Presenter{
    onButtonClick()
}
IPresenter <|-r- Presenter
note top of Presenter: Реализует \nработу с UI

/'
interface IView{
    displayInfo()
}
class View
IView <|-r- View
Presenter .u.> IView
'/
interface IUseCase{
    runCommand(): CommandResult
    runQuery(): QueryResult
}
class UseCase
IUseCase <|-d- UseCase

UseCase ..> IDomainEntity

class Controller{
    onBusinessEvent()
}

Controller .l.> IUseCase
UseCase .l.> IRepository
Controller .u.> IPresenter

Presenter .d.> Controller

@enduml