@startuml
'https://plantuml.com/class-diagram

interface IDomainEntity{
    domainProperty: Int
    domainOperation()
}
class DomainEntity
DomainEntity -r-|> IDomainEntity

interface IRepository{
    save()
    get()
    delete()
}

class Repository
IRepository <|-l- Repository
note bottom of Repository: Реализует \nработу с БД

interface IPresenter{
    formatViewModel()
}

class Presenter{

}
IPresenter <|-r- Presenter


interface IUseCase{
    runCommand(): CommandResult
    runQuery(): QueryResult
}
class UseCase
IUseCase <|-d- UseCase

UseCase ..> IDomainEntity

class Controller{
    onBusinessEvent(): ViewModel
}

Controller .l.> IUseCase
UseCase .l.> IRepository
Controller .u.> IPresenter

class UI{
    onButtonClick()
}
note right of UI: Реализует \nработу с UI

UI .l.> Controller

@enduml